version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "5002:5000"
    environment:
      - PREDICTION_SERVICE_URL=http://prediction_service:80

  prediction_service:
    build: ./prediction_service
    ports:
      - "5001:80"