name: Run training

on:
  workflow_dispatch:

jobs:
  training:
    name: Training
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.10.12"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r model/requirements.txt

    - name: Create a new run
      run: |
        MLFLOW_RUN_ID=$(python model/training/run.py)
        echo "MLFLOW_RUN_ID=$MLFLOW_RUN_ID" >> $GITHUB_ENV

    - name: Download dataset
      run: python model/training/download_dataset.py

    - name: Prepare dataset
      run: python model/training/preprocessing.py
