name: Run training

on:
  workflow_dispatch:

env:
  MLFLOW_TRACKING_URI: databricks

jobs:
  training:
    name: Training
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.10.12"
    - name: Install dependencies
      run: |
        pip install mlflow==2.14.2
  
    - name: Create a new run
      run: |
        MLFLOW_RUN_ID=$(python model/training/create_run.py)
        echo "MLFLOW_RUN_ID=$MLFLOW_RUN_ID" >> $GITHUB_ENV
      env:
        MLFLOW_TRACKING_URI: ${{ env.OUT_CONTAINER_MLFLOW_TRACKING_URI }}

    - name: Create Docker image
      run: docker build -t training -f model/training.dockerfile ./model

    - name: Download dataset
      run: docker run -it -e MLFLOW_TRACKING_URI -e MLFLOW_RUN_ID -v ./temp_data/:/app/temp_data/ --network=shared_network training python training/download_dataset.py

    - name: Preprocess
      run: docker run -it -e MLFLOW_TRACKING_URI -e MLFLOW_RUN_ID -v ./temp_data/:/app/temp_data/ --network=shared_network training python training/preprocessing.py

    - name: Run training
      run: docker run -it -e MLFLOW_TRACKING_URI -e MLFLOW_RUN_ID --network=shared_network training python training/train_model.py
